# Generated by Django 2.2 on 2023-03-06 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='PrimaryDate',
        ),
    ]
